# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20160422_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valueName', models.CharField(max_length=15)),
                ('unit', models.CharField(max_length=15)),
                ('value', models.IntegerField()),
                ('createTime', models.DateTimeField()),
                ('safe', models.BooleanField(default=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Custom', to='data.Sensors')),
            ],
            options={
                'ordering': ('-createTime',),
            },
        ),
    ]
