# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20160422_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voltage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(default='V', max_length=15)),
                ('value', models.IntegerField()),
                ('createTime', models.DateTimeField()),
                ('safe', models.BooleanField(default=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Voltage', to='data.Sensors')),
            ],
            options={
                'ordering': ('-createTime',),
            },
        ),
        migrations.RemoveField(
            model_name='supersonicsounding',
            name='sensor',
        ),
        migrations.DeleteModel(
            name='Supersonicsounding',
        ),
    ]
